create table admin_upload_video(
    id  int not null PRIMARY KEY AUTO_INCREMENT,
    wechat_code varchar(255),
    video_id int,
    video_img_id int,
    update_time datetime,
    user_download_count int);

create table FILE_ADDR(
    id  int not null PRIMARY KEY AUTO_INCREMENT,
    addr varchar(255),
    whole_addr int,
    file_type int,
    original_file_name  varchar(255)
);

create table user_upload_info(
    id  int not null PRIMARY KEY AUTO_INCREMENT,
    wechat_code varchar(255),
    before_img_1 int,
    before_img_2 int,
    before_video_1 int,
    before_video_img_1 int,
    before_video_2 int,
    before_video_img_2 int,
    install_img_1 int,
    install_img_2 int,
    install_video_1 int,
    install_video_img_1 int,
    install_video_2 int,
    install_video_img_2 int,
    install_video_3 int,
    install_video_img_3 int,
    install_video_4 int,
    install_video_img_4 int,
    display_img_1 int,
    display_img_2 int,
    display_img_3 int,
    display_img_4 int,
    display_img_5 int,
    display_img_6 int,
    display_video_1 int,
    display_video_img_1 int,
    display_video_2 int,
    display_video_img_2 int,
    display_video_3 int,
    display_video_img_3 int,
    display_video_4 int,
    display_video_img_4 int,
    display_video_5 int,
    display_video_img_5 int,
    display_video_6 int,
    display_video_img_6 int,
    dispose_video_1 int,
    dispose_video_img_1 int,
    dispose_video_2 int,
    dispose_video_img_2 int,
    dispose_video_3 int,
    dispose_video_img_3 int,
    dispose_video_4 int,
    dispose_video_img_4 int,
    dispose_video_5 int,
    dispose_video_img_5 int,
    dispose_video_6 int,
    dispose_video_img_6 int,
    file_change int,
    zip_url varchar(255)
);