spring:
  application:
    name: cat-upload-file-web.online
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
file:
  root-path: /Users/wangshuo/IdeaGitProjects/cat_no_roll/files

